---
title: "SURV 727 Assignment 4"
author: "Mathew Hill"
date: "2024-10-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#| include: false 
library(tidyverse)
library(DBI)
library(dbplyr)
library(bigrquery)
```

After you have initialized a project, paste your project ID into the following chunk.
```{r}
project <- "surv-727-project-4"
```

We will connect to a public database, the Chicago crime database, which has data on crime in Chicago.
```{r}
con <- dbConnect(
  bigrquery::bigquery(),
  project = "bigquery-public-data",
  dataset = "chicago_crime",
  billing = project
)
con
```

```{r}
dbListTables(con)
```


Write a first query that counts the number of rows of the ‘crime‘ table in the year 2016. Use code chunks with {sql connection = con} in order to write SQL code within the document
```{sql connection = con}
SELECT count(primary_type), count(*)
FROM crime
WHERE year = 2016
LIMIT 10
```





